### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by jbenet** [npat-efault/poller#1]
If i'm not mistaken, this wont work in bsds/osx, as they dont have Epoll. would be amazing to make `poller` a cross-platform solution

**Comment by npat-efault** [comment]
Support for most Unix-like systems added at [Release 2.0.0](https://github.com/npat-efault/poller/releases/tag/v2.0.0), using a fallback select(2) implementation.

**Comment by jbenet** [comment]
I don't recall the specifics of this module but you might want to use epoll as select has mimits

**Comment by npat-efault** [comment]
poller **does use** epoll(7) where available (Linux). 

select(2) is used as a **fallback** implementation for systems that don't have epoll. Limitations on select(2) are on the number of FDs (which could be overcome) and certainly on performance (linear searches for activity). These limitation, while present, are not _that_ restrictive. Again, this is a _fallback implementation_ to cover as many POSIX systems as possible. In this sense, the limitations are, I think, reasonable.

Ideally, system-specific io-multiplexing or async-io facilities (e.g. kqueue(2), or /dev/poll(7)) should be used to provide higher performance implementations for other systems. This is **already** the case for Linux, which is the platform I (personally) am mostly interested in.

**Comment by jbenet** [comment]
Ah sorry I meant kqueue :)

the fd limit is pretty bad-- original reason I needed this was for large
numbers of net sockets.

Ill link to https://github.com/jbenet/go-reuseport/tree/master/poll which
is a brain damaged impl that's wasteful but lifts the limitation (uses
kqueue and epoll)

@whyrusleeping did we ever impl that fix to reduce socket usage?

**Comment by npat-efault** [comment]
Yes, a kqueue based impl. would certainly be useful. If I find some time I may add one.
