### ISSUE TITLE
Close method is unsafe.

### ISSUE THREAD

**Issue by jaracil** [npat-efault/poller#3]
If Close method is called more than one time then the second call could close an invalid or in use file descriptor.

I think this method must check fd.closed flag:

```go
func (fd *FD) Close() error {
	// Take both locks, to exclude read and write operations from
	// accessing a closed sysfd.
	if err := fd.Lock(); err != nil {
		debugf("FD %03d: CL: Closed", fd.id)
 		return err
 	}
 	defer fd.Unlock()
+	if fd.closed {
+		return ErrClosed
+	}
 	fd.closed = true
        ...
```   

Thanks.

**Comment by npat-efault** [comment]
No it is not (unsafe). 

The suggested check is not required, since it is already preformed inside fd.Lock().

**Comment by jaracil** [comment]
Ops! You are right. ;)
