### ISSUE TITLE
failed to build for freebsd without cgo

### ISSUE THREAD

**Issue by vtolstov** [npat-efault/poller#5]
github.com/npat-efault/poller/poller_select.go:29: undefined: fdSet

**Comment by vtolstov** [comment]
#4 i think helps a lot

**Comment by npat-efault** [comment]
As stated in the documentation: "The select(2)-based implementation uses CGo for some ancillary select-related operations". So this is not an issue.

Does it build and work ok _with_ CGo?

(The kqueue-based impl, when added, will not require CGo)

**Comment by vtolstov** [comment]
I can't use cgo, when you expect to add kqueue support?
26 нояб. 2015 г. 16:37 пользователь "Nick Patavalis" <
notifications@github.com> написал:

**Comment by npat-efault** [comment]
Why can't you use cgo?
Kqueue support: Soon.

**Comment by vtolstov** [comment]
I'm crosscompile from Linux to netbsd and freebsd
27 нояб. 2015 г. 16:28 пользователь "Nick Patavalis" <
notifications@github.com> написал:
